substitutions:
  device_name: lichtimbus
  device_friendlyName: Licht im Bus

esphome:
  name: $device_name
  platform: esp32
  board: az-delivery-devkit-v4

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${device_friendlyName} Hotspot
    password: !secret ap_password

captive_portal:

## SENSORS
binary_sensor:
  - platform: gpio
    id: btn_lights_main
    pin:
      number: 2
      inverted: true
    on_multi_click:
      - timing:
          - ON for at most 0.5s
          - OFF for at most 0.2s
          - ON for at most 0.5s
          - OFF for at most 0.2s
          - ON for at most 0.5s
          - OFF for at least 0.5s
        then:
          - logger.log: "Tripple Clicked - Lights on 100"
          - light.turn_on:
              id: lights_main
              brightness: 100%
      - timing:
          - ON for at most 0.5s
          - OFF for at most 0.2s
          - ON for at least 0.5s
        then:
          - logger.log: "Double Clicked and holding - Dimm Lights up"
          - while:
              condition:
                binary_sensor.is_on: btn_lights_main
              then:
                - light.dim_relative:
                    id: lights_main
                    relative_brightness: 0.3%
                    transition_length: 0.01s
                - delay: 0.01s
      - timing:
          - ON for at least 0.5s
        then:
          - logger.log: "Single Clicked and holding - Dimm Lights down"
          - while:
              condition:
                binary_sensor.is_on: btn_lights_main
              then:
                - light.dim_relative:
                    id: lights_main
                    relative_brightness: -0.3%
                    transition_length: 0.01s
                - delay: 0.01s
      - timing:
          - ON for at most 1s
          - OFF for at least 0.5s
        then:
          - logger.log: "Single Short Clicked - Toggle Lights"
          - light.toggle:
              id: lights_main
              transition_length: 3s

## LIGHTS
light:
  - platform: monochromatic
    id: lights_main
    name: All Lights
    output: main_pwm_output
    effects:
      - pulse:
          name: Slow Pulse
          transition_length: 5s
          update_interval: 5s
      - flicker:
          name: Flicker Effect
          alpha: 95%
          intensity: 1.5%
      - strobe:
          name: Strobe Effect
          colors:
            - state: True
              brightness: 100%
              duration: 2s
            - state: True
              brightness: 30%
              duration: 500ms

## OUTPUTS
output:
  - platform: template
    id: main_pwm_output
    type: float
    write_action:
      - lambda: "id(main_pwm_output_gpio).set_level(state == 0 ? 0 : 0.023 + state * (1 - 0.023));"
  - platform: ledc
    id: main_pwm_output_gpio
    pin: 5
